# Generated by Django 3.2.12 on 2022-02-21 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0002_auto_20220221_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_ts',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated Date'),
        ),
    ]
