# Generated by Django 3.2.12 on 2022-02-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0003_auto_20220221_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'orders'},
        ),
        migrations.AlterModelTable(
            name='cart',
            table='fo_cart',
        ),
        migrations.AlterModelTable(
            name='category',
            table='fo_category',
        ),
        migrations.AlterModelTable(
            name='item',
            table='fo_items',
        ),
        migrations.AlterModelTable(
            name='order',
            table='fo_order',
        ),
    ]
