# Generated by Django 3.2.12 on 2022-02-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0004_auto_20220222_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_ts',
        ),
    ]
