# Generated by Django 3.2.12 on 2022-02-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0005_remove_order_updated_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
