# Generated by Django 3.2.12 on 2022-02-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0006_alter_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_ts',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated Date'),
        ),
    ]
